#! /bin/sh
# bootstrap: Script for setting up the repository for use.
# Copyright (C) 2023 streaksu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

if ! [ -d source/flanterm ]; then
    git clone https://github.com/mintsuki/flanterm.git source/flanterm
    cd source/flanterm
    git checkout f95f5584fb87577908beff8cbe0f68fee8940517
    cd ../..
fi

mkdir -p build-aux
cp "$(automake --print-libdir)/install-sh" build-aux

autoreconf -fvi -Wall
